"""Initial migration

Revision ID: e8e6130d4de1
Revises: 
Create Date: 2025-01-19 21:02:21.907828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e6130d4de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cam_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('cam_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cam_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('Cam_id')

    op.create_table('complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('file_data', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
